### ISSUE TITLE
Add grid to the board

### ISSUE THREAD

**Issue by vahnag** [ovidiuch/flatris#46]
It would be great to have a subtle grid on the board to make it easier to see where the block is going. Or is this against the rules?

**Comment by skidding** [comment]
I think a grid might not look good visually, but I understand your pain. I have another friend who complains about not seeing where the piece is going to fall, and while it is part of the game's difficulty, I am considering implementing a "drop shadow" in the future, which shows you exactly where the piece will fall from the current position. Eg.

![image](https://user-images.githubusercontent.com/250750/37280557-b2b2a40c-2620-11e8-952b-933fac80634c.png)
